formatter: markdown table

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

content: |-
  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

settings:
  anchor: false
  color: false
  escape: true
  indent: 3
  required: true
  sensitive: false
  type: true
