variable "name_prefix" {
  description = "Prefix for every resource name, for example nnat-dev."
  type        = string
}

variable "log_groups" {
  description = "Short names that get a log group named /<name_prefix>/<name> (api, web, migrate)."
  type        = set(string)
}

variable "alarmed_services" {
  description = "ECS services (named <name_prefix>-<service>) that get CPU, memory, task-count and 5xx alarms."
  type        = set(string)
}

variable "retention_days" {
  description = "Log retention in days."
  type        = number
}

variable "cluster_name" {
  description = "ECS cluster name, for alarm dimensions."
  type        = string
}

variable "alb_arn_suffix" {
  description = "Load balancer ARN suffix, for alarm dimensions."
  type        = string
}

variable "target_group_arn_suffixes" {
  description = "Target group ARN suffixes keyed by service name."
  type        = map(string)
}

variable "rds_instance_id" {
  description = "RDS instance identifier, for alarm dimensions."
  type        = string
}

variable "kms_key_arn" {
  description = "Customer-managed KMS key for log groups and the SNS topic. Its policy must allow the logs and cloudwatch services."
  type        = string
  default     = null
}

variable "alarm_email" {
  description = "Email address subscribed to the alarm topic. Empty creates no subscription (the recipient must confirm it)."
  type        = string
  default     = ""
}

variable "alb_5xx_threshold" {
  description = "5xx responses generated by the load balancer, per 5 minutes, before alarming."
  type        = number
  default     = 10
}

variable "cpu_threshold_percent" {
  description = "CPU utilisation percent before alarming (ECS and RDS)."
  type        = number
  default     = 80
}

variable "memory_threshold_percent" {
  description = "ECS memory utilisation percent before alarming."
  type        = number
  default     = 80
}

variable "rds_free_storage_gib" {
  description = "Free database storage in GiB below which to alarm."
  type        = number
  default     = 5
}
